# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

cache:
  directories:
    - $HOME/.pip-cache/
    - $HOME/virtualenv/python2.7
    - $HOME/virtualenv/python2.7.8

install:
  - pip install -r requirements.txt  --download-cache $HOME/.pip-cache

before_script:
  - make lint

script:
  - make test